In [1]:
# import libraries
import numpy as np
import torch

# Using Numpy

In [16]:
# Create a Vector
nv = np.array([[1,2,3,4]])
print('NumPy Array:',nv)
print('')

# Transpose the vector
print('Transposed Array:',nv.T)
print('')

# Transpose the Transpose! 
nv_T_T = (nv.T).T
print('Transposing the Transpose:', nv_T_T)

NumPy Array: [[1 2 3 4]]

Transposed Array: [[1]
 [2]
 [3]
 [4]]

Transposing the Transpose: [[1 2 3 4]]


In [23]:
# repeat for a matrix

nM = np.array([[1,2,3,4],
               [5,6,7,8]])
print(nM)
print('')

# transpose it
print(nM.T), print('')

# transpose the transpose
nM_T_T = (nM.T).T
print(nM_T_T)

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]


# Using PYTORCH

In [27]:
# create a vector
tv = torch.tensor([[1,2,3,4]])
print(tv)
print(' ')

# transpose it
print(tv.T)
print('')

# transpose the transpose
tv_T = (tv.T).T
print(tv_T)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])

tensor([[1, 2, 3, 4]])


In [28]:
# repeat for a matrix
tM = torch.tensor([ [1,2,3,4],[5,6,7,8] ])
print(tM), print(' ')

# transpose it
print(tM.T), print(' ')

# transpose the transpose!
tMT = tM.T
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [31]:
# examine the data types

print(f'Variable nv is of type {type(nv)}')
print(f'Variable nv is of type {type(nM)}')
print(f'Variable nv is of type {type(tv)}')
print(f'Variable nv is of type {type(tM)}')

Variable nv is of type <class 'numpy.ndarray'>
Variable nv is of type <class 'numpy.ndarray'>
Variable nv is of type <class 'torch.Tensor'>
Variable nv is of type <class 'torch.Tensor'>
